# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njGIswsStAL3jcI4rNND0938LKmEPUph

## 1. Setup
Install the libraries needed for training (scikit-learn, shap)
and plotting (matplotlib).
"""

!pip install scikit-learn pandas joblib shap matplotlib -q

"""## 2. Load data
Upload the BRFSS 2014 survey extract. Target column is DIABETES
(Yes/No), 25 categorical predictor columns.
"""

from google.colab import files
uploaded = files.upload()  # pick BFRSS_2014_modified.csv

"""## 3. Train the model
Model choice: Random Forest, 300 trees. It handles class imbalance (~18% "Yes")
via class_weight="balanced". It alos runs SHAP to explain which
survey questions drive the prediction.
"""

"""
Trains a diabetes-risk classifier on BRFSS 2014 survey data and saves
a ready-to-serve pipeline (preprocessing + model) to model.joblib.

Run: python train_model.py
"""

import pandas as pd
import numpy as np
import joblib
import shap
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score

DATA_PATH = "BFRSS_2014_modified.csv"
TARGET = "DIABETES"
DROP_COLS = ["HLTHPLN1"]  # constant column, no signal

df = pd.read_csv(DATA_PATH)
df = df.drop(columns=DROP_COLS)
df = df.dropna(subset=["HLTHCVR1"])  # small number of missing rows

X = df.drop(columns=[TARGET])
y = (df[TARGET] == "Yes").astype(int)

feature_cols = X.columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(handle_unknown="ignore"), feature_cols)]
)

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1,
)

pipeline = Pipeline(steps=[("preprocess", preprocessor), ("model", model)])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred, target_names=["No", "Yes"]))
print("ROC AUC:", round(roc_auc_score(y_test, y_proba), 4))

joblib.dump(pipeline, "model.joblib")

# Save the option lists so the Streamlit app can build matching dropdowns
options = {col: sorted(X[col].dropna().unique().tolist()) for col in feature_cols}
joblib.dump({"feature_cols": feature_cols, "options": options}, "input_schema.joblib")

print("Saved model.joblib and input_schema.joblib")

# ---------------------------------------------------------------------------
# SHAP: which features actually drive the model's predictions?
#
# TreeExplainer walks the forest's trees directly (fast, exact for tree
# models). It returns one SHAP value per encoded one-hot column per row,
# per class. A positive value pushes the prediction toward "Yes" (diabetes),
# negative pushes toward "No". We only need this on a sample, not all 94k
# training rows, to get a stable global picture.
# ---------------------------------------------------------------------------
preprocess = pipeline.named_steps["preprocess"]
forest = pipeline.named_steps["model"]
encoded_names = preprocess.named_transformers_["cat"].get_feature_names_out(feature_cols)

sample = X_train.sample(n=min(500, len(X_train)), random_state=42)
sample_encoded = preprocess.transform(sample).toarray()

explainer = shap.TreeExplainer(forest)
shap_values = explainer.shap_values(sample_encoded)  # shape: (rows, encoded_cols, classes)
shap_for_yes = shap_values[:, :, 1]  # keep only the "Yes" (diabetes) class

# Collapse the one-hot columns back to their original survey question so the
# chart reads "GENHLTH" instead of "GENHLTH_Poor", "GENHLTH_Fair", etc.
importance_by_feature = {}
for col in feature_cols:
    col_mask = [i for i, name in enumerate(encoded_names) if name.startswith(f"{col}_")]
    importance_by_feature[col] = np.abs(shap_for_yes[:, col_mask]).mean()

ranked = sorted(importance_by_feature.items(), key=lambda kv: kv[1], reverse=True)
top15 = ranked[:15]

plt.figure(figsize=(8, 6))
plt.barh([k for k, _ in top15][::-1], [v for _, v in top15][::-1], color="#2E7D32")
plt.xlabel("Mean |SHAP value| (average impact on predicted diabetes risk)")
plt.title("Which survey questions matter most to the model")
plt.tight_layout()
plt.savefig("shap_importance.png", dpi=150)
print("Saved shap_importance.png")

print("\nTop 10 features by SHAP importance:")
for name, val in top15[:10]:
    print(f"  {name:<15} {val:.4f}")

files.download("model.joblib")
files.download("input_schema.joblib")

files.download("shap_importance.png")